#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1550660048                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Pivot App                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 7 day Free Trial, then 1.99 £/$/€                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Easy Pivot Tables on iOS

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Luke Stringer                           
your_link                                 : https://twitter.com/lukestringer90                     
your_city                                 : Sheffield, UK                                
email_address                             : luke@getpivot.app
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : GetPivotApp
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Build Pivot Tables
    description                           : Select one of more fields to build a multi-level pivot table just like Excel or Google Sheets.
    fontawesome_icon_name                 : table
    
  - title                                 : Sort & Filter
    description                           : Apply filters to a pivot table. Sort on title, sum or count value.
    fontawesome_icon_name                 : filter

  - title                                 : Visualise using Graphs
    description                           : See pivot table data as a bar grpah or pie chart.
    fontawesome_icon_name                 : chart-pie

  - title                                 : Export your Data
    description                           : Share pivot tables and graphs with other as a PDF report.
    fontawesome_icon_name                 : file-export

  - title                                 : Import CSVs
    description                           : Open CSVs in Pivot App from the built in document browser, or extneral apps such as File, DropBox etc.
    fontawesome_icon_name                 : file-csv
  
  - title                                 : iPad and iPhone
    description                           : All features supported on iPhone and iPad.
    fontawesome_icon_name                 : mobile-alt



# Theme Settings
topbar_color                              : "#25935D"
topbar_transparency                       : 0.5
topbar_title_color                        : "#ffffff"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#272428"
cover_overlay_transparency                : 1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#25935D"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#c8c8c8"

feature_icons_foreground_color            : "#25935D"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#25935D"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#c8c8c8"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
